MONGODB_HOST: mongodb-{{ env }}.devopspractice.shop
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.devopspractice.shop
USER_HOST: user.backend-alb-{{ env }}.devopspractice.shop
CART_HOST: cart.backend-alb-{{ env }}.devopspractice.shop 
PAYMENT_HOST: payment.backend-alb-{{ env }}.devopspractice.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.devopspractice.shop
MYSQL_HOST: mysql-{{ env }}.devopspractice.shop
REDIS_HOST: redis-{{ env }}.devopspractice.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.devopspractice.shop 
