MONGODB_HOST: mongodb-{{ env }}.devopspractice.shop
CATALOGUE_HOST: catalogue-{{ env }}.devopspractice.shop
USER_HOST: user-{{ env }}.devopspractice.shop
CART_HOST: cart-{{ env }}.devopspractice.shop 
PAYMENT_HOST: payment-{{ env }}.devopspractice.shop
SHIPPING_HOST: shipping-{{ env }}.devopspractice.shop
MYSQL_HOST: mysql-{{ env }}.devopspractice.shop
REDIS_HOST: redis-{{ env }}.devopspractice.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.devopspractice.shop 
